name: codacy

on: push

jobs:
  check:
    name: Codacy Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: install deps
        run: npm i ci --also:dev
      - name: Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@4.0.0       
        with:
          project_token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          upload: true
